name: Wesclin Baseball 2017
favicon: null
layout_spectrum: 0.46742
typography_spectrum: 0.53691
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefff9'
    - '#000411'
    - '#736f72'
    - '#373a35'
    - '#a82c20'
  brandStrength: 0.9169446367304772
  lightness: 0.42436935170553625
  saturation: 0.5024226151872426
  rhythmicContrast: 0.5
purpose: []
